# Introduction

Depuis la naissance de la psychothérapie à la fin du 19ème siècle, la prise en charge psychologique des patients a connu une expansion et une diversification significative. L’apparition de nouvelles pathologies et l’évolution des mentalités a induit un réaménagement de l’offre de soins et des techniques proposées. Ce début de 21ème siècle a connu une influence du modèle managérial qui tente d’équilibrer les besoins et les ressources et conçoit la société comme un système au sein duquel les individus et les produits circulent suivant des canaux idéalement prédéfinis. La santé mentale n’échappe actuellement pas à cette grille de lecture. Par exemple, la “schizophrénie” est un problème social qui doit être géré par des infrastructures et des professionnels qui adoptent une technique de soin définie. Ainsi pourrait-on construire un hôpital psychiatrique répondant aux normes architecturales, engager des psychiatres qui sont porteurs d’un diplôme officiel et les encourager à proposer des soins cohérents avec la littérature scientifique la plus actuelle. Un tel modèle a notamment pour intérêt d’objectiver des coûts et des bénéfices au modèle de soins.\
Les (projets de) lois sur le titre de psychothérapeute s’inscrivent dans une perspective managériale de gestion de la souffrance psychique de la population. Cette perspective nécessite dès lors à objectiver cette souffrance : combien de personnes souffrent-elles de dépression, d’anxiété ou encore de tendances suicidaires ? Des études scientifiques doivent alors être menées pour répondre à ces questions. Par la suite, il s’agit de proposer une technique validée de résolution du problème afin de guérir les patients du trouble dont ils souffrent. Ce modèle d’intervention a des avantages : il suit une logique rationnelle, il vise la transparence des interventions, il ajuste les coûts (notamment financiers) avec les besoins, il vise l’efficience et il est généralement compatible avec le mode de décision des responsables politiques. Il présente toutefois également des inconvénients : il induit une hégémonie managériale qui phagocyte les autres grilles de lectures d’un problème en le simplifiant, il priorise la question financière avant les autres considérations (par exemple éthiques) et il conçoit les professionnels comme des rouages d’un système au sein duquel ils doivent se contenter de jouer le rôle qui leur a été assigné. Il ne nous revient pas ici de faire le procès de ce modèle. Nous souhaitons plutôt nous intéresser à une de ces conséquences : la subordination des professionnels de la santé mentale par rapport au patient et à la technique de soins. Dit autrement, il est attendu que le pourvoyeur de soins soit un technicien scrupuleux afin de guérir le patient en souffrance. Selon nous, cette conception simplifie le rôle de soignant et évince le vécu de celui-ci. Derrière chaque professionnel se cache une personne distincte des autres et termes de personnalité, de croyances, de motivations, d’intérêts et d’émotions.\
Ainsi avons-nous souhaité nous intéresser au vécu du professionnel dans la relation qui l’unit avec le patient. Quels sont les pensées, les comportements et les émotions suscitées par la rencontre thérapeutique ? Cette question nous semble primordiale car elle replace le professionnel comme être humain face à un autre être humain. Elle est susceptible de mettre en lumière les joies et les difficultés du travail thérapeutique qui ont un lien avec le besoin de reconnaissance professionnelle intrinsèque à tout travail social. Ce vécu du professionnel est-il un obstacle ou un appui dans sa pratique ? Doit-il le dépasser ou l’intégrer dans son traitement ? Ces questions nous ont amené à nous intéresser au thème du contre-transfert. En quoi consiste-t-il ? Y aurait-il moyen de l’évaluer de manière rigoureuse ? Si oui, que nous apprendrait un outil mesurant ce contre-transfert ? Notre texte vise à aborder ces questions. Nous allons dès lors aborder la genèse du concept de contre-transfert et son évolution dans le temps jusqu’à aujourd’hui afin d’en proposer une définition. Nous proposerons ensuite un questionnaire francophone qui vise à mesurer le vécu contre-transférentiel de professionnels soignants. Nous présenterons les propriétés psychométriques de l’instruments, ses apports et ses limites. Nous proposerons certaines pistes théoriques afin d’utiliser les résultats du questionnaire à des fins cliniques et thérapeutiques.
